allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  lefthook: true
  msw: true
  sharp: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@shadcn/react@0.1.0'
