import {
    IconAlertOctagon,
    IconAlertTriangle,
    IconArrowLeft,
    IconArrowRight,
    IconBrightness,
    IconCheck,
    IconChevronDown,
    IconChevronLeft,
    IconChevronRight,
    IconChevronUp,
    IconCircleCheck,
    IconClock,
    IconCommand,
    IconCreditCard,
    IconCube3dSphere,
    IconDeviceLaptop,
    IconDots,
    IconEye,
    IconEyeOff,
    IconHome,
    IconInfoCircle,
    IconLayoutDashboard,
    IconLayoutSidebar,
    IconLoader,
    IconMinus,
    IconMoon,
    IconPalette,
    type IconProps,
    IconSearch,
    IconSelector,
    IconSettings,
    IconSun,
    IconUser,
    IconX,
} from "@tabler/icons-react";

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
    clock: IconClock,
    brightness: IconBrightness,
    eye: IconEye,
    eyeOff: IconEyeOff,
    palette: IconPalette,
    logo: IconCommand,
    circleCheck: IconCircleCheck,
    infoCircle: IconInfoCircle,
    alertTriangle: IconAlertTriangle,
    alertOctagon: IconAlertOctagon,
    loader: IconLoader,
    arrowLeft: IconArrowLeft,
    arrowRight: IconArrowRight,
    cube3dSphere: IconCube3dSphere,
    layoutSidebar: IconLayoutSidebar,
    x: IconX,
    check: IconCheck,
    chevronUp: IconChevronUp,
    chevronDown: IconChevronDown,
    chevronLeft: IconChevronLeft,
    chevronRight: IconChevronRight,
    dots: IconDots,
    selector: IconSelector,
    minus: IconMinus,
    search: IconSearch,
    sun: IconSun,
    moon: IconMoon,
    laptop: IconDeviceLaptop,
    dashboard: IconLayoutDashboard,
    user: IconUser,
    creditCard: IconCreditCard,
    settings: IconSettings,
    home: IconHome,
};
